name: Redis-Adapter-Build-Test

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - "6379:6379"
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Start Redis server
        run: |
          export REDIS_HOST="127.0.0.1"

      - name: Run go test
        run: |
          cd redis-adapter/
          go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          working-directory: redis-adapter/
